package com.studyplatform.export;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfWriter;
import com.studyplatform.entity.StudyGuide;
import com.studyplatform.exception.ApiException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.ByteArrayOutputStream;

@Service
@RequiredArgsConstructor
@Slf4j
public class PdfExportService {

    private final ObjectMapper objectMapper;

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 22, Font.BOLD, new Color(26, 26, 26));
    private static final Font H2_FONT = new Font(Font.HELVETICA, 16, Font.BOLD, new Color(51, 51, 51));
    private static final Font H3_FONT = new Font(Font.HELVETICA, 12, Font.BOLD, new Color(51, 51, 51));
    private static final Font BODY_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, new Color(51, 51, 51));
    private static final Font META_FONT = new Font(Font.HELVETICA, 9, Font.ITALIC, new Color(102, 102, 102));
    private static final Font CODE_FONT = new Font(Font.COURIER, 9, Font.NORMAL, new Color(51, 51, 51));
    private static final Font KEY_FONT = new Font(Font.HELVETICA, 10, Font.BOLD, new Color(200, 164, 78));

    public byte[] exportGuide(StudyGuide guide) {
        try {
            JsonNode content = objectMapper.readTree(guide.getContent());
            ByteArrayOutputStream baos = new ByteArrayOutputStream();

            com.lowagie.text.Document doc = new com.lowagie.text.Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(doc, baos);
            doc.open();

            // Title
            Paragraph title = new Paragraph(guide.getTitle(), TITLE_FONT);
            title.setSpacingAfter(8);
            doc.add(title);

            // Metadata line
            String meta = guide.getExpertiseLevel().name() + " level";
            if (guide.getTotalEstimatedMinutes() > 0) {
                meta += " | Estimated: " + guide.getTotalEstimatedMinutes() + " minutes";
            }
            Paragraph metaPara = new Paragraph(meta, META_FONT);
            metaPara.setSpacingAfter(20);
            doc.add(metaPara);

            // Divider
            doc.add(new Paragraph(" "));

            // Modules
            if (content.has("modules") && content.get("modules").isArray()) {
                int moduleNum = 1;
                for (JsonNode module : content.get("modules")) {
                    addModule(doc, module, moduleNum++);
                }
            }

            // Footer
            doc.add(new Paragraph(" "));
            Paragraph footer = new Paragraph(
                    "Generated by StudyPlatform — AI-Powered Study Ecosystem", META_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            doc.add(footer);

            doc.close();
            log.info("PDF exported for guide: {} ({} bytes)", guide.getTitle(), baos.size());
            return baos.toByteArray();

        } catch (Exception e) {
            log.error("PDF export failed for guide {}: {}", guide.getId(), e.getMessage());
            throw ApiException.badRequest("Failed to generate PDF: " + e.getMessage());
        }
    }

    private void addModule(com.lowagie.text.Document doc, JsonNode module, int num) throws DocumentException {
        String moduleTitle = module.has("title") ? module.get("title").asText() : "Module " + num;
        String type = module.has("type") ? module.get("type").asText() : "";
        int minutes = module.has("estimatedMinutes") ? module.get("estimatedMinutes").asInt() : 0;

        // Module header
        Paragraph header = new Paragraph("Module " + num + ": " + moduleTitle, H2_FONT);
        header.setSpacingBefore(20);
        header.setSpacingAfter(4);
        doc.add(header);

        // Module meta
        String moduleMeta = type;
        if (minutes > 0) moduleMeta += " | ~" + minutes + " min";
        if (!moduleMeta.isEmpty()) {
            Paragraph mp = new Paragraph(moduleMeta, META_FONT);
            mp.setSpacingAfter(10);
            doc.add(mp);
        }

        // Key concept box
        if (module.has("keyConceptBox") && !module.get("keyConceptBox").isNull()) {
            Paragraph key = new Paragraph("Key Concept: " + module.get("keyConceptBox").asText(), KEY_FONT);
            key.setSpacingAfter(10);
            doc.add(key);
        }

        // Content — render Markdown-ish content as plain text paragraphs
        if (module.has("content")) {
            String contentText = module.get("content").asText();
            for (String line : contentText.split("\n")) {
                line = line.trim();
                if (line.isEmpty()) {
                    doc.add(new Paragraph(" "));
                } else if (line.startsWith("### ")) {
                    Paragraph h3 = new Paragraph(line.substring(4), H3_FONT);
                    h3.setSpacingBefore(10);
                    h3.setSpacingAfter(4);
                    doc.add(h3);
                } else if (line.startsWith("## ")) {
                    Paragraph h2 = new Paragraph(line.substring(3), H2_FONT);
                    h2.setSpacingBefore(12);
                    h2.setSpacingAfter(6);
                    doc.add(h2);
                } else if (line.startsWith("```")) {
                    // Skip code fence markers (content between them renders as code)
                } else if (line.startsWith("    ") || line.startsWith("\t")) {
                    Paragraph code = new Paragraph(line, CODE_FONT);
                    code.setIndentationLeft(20);
                    doc.add(code);
                } else if (line.startsWith("- ") || line.startsWith("* ")) {
                    Paragraph bullet = new Paragraph("  " + line, BODY_FONT);
                    bullet.setIndentationLeft(15);
                    doc.add(bullet);
                } else {
                    Paragraph p = new Paragraph(line.replaceAll("\\*\\*(.*?)\\*\\*", "$1")
                            .replaceAll("\\*(.*?)\\*", "$1"), BODY_FONT);
                    p.setSpacingAfter(4);
                    doc.add(p);
                }
            }
        }
    }
}
